global using System.Numerics;
global using Dalamud.Interface.Utility;
global using ImGuiNET;
global using RotationSolver.Basic.Actions;
global using RotationSolver.Basic.Attributes;
global using RotationSolver.Basic.Data;
global using RotationSolver.Basic.Helpers;
global using RotationSolver.Basic.Rotations;
global using RotationSolver.Basic.Rotations.Basic;
